#! /bin/bash

docker run --rm -t -i \
    -v $PWD/bin:/home/mitmproxy/bin \
    -v $PWD/data/mitmproxy:/home/mitmproxy/.mitmproxy \
    hild1.no:mitmphantom middag.hild1.no

# docker run --rm -it -v $PWD/mitmproxy:/home/mitmproxy/.mitmproxy 
# -p 127.0.0.1:8081:8081 -p 8080:8080 mitmproxy/mitmproxy mitmweb --web-iface 0.0.0.0
